// ─── ICS Calendar Export Utilities ────────────────────────────

export interface CalendarTask {
  id: string;
  task: string;
  notes?: string;
  nextDueDate: Date | null;
  intervalMonths: number;
}

/**
 * Format a Date as an ICS DATE value (YYYYMMDD).
 */
function formatICSDate(date: Date): string {
  const y = date.getFullYear();
  const m = String(date.getMonth() + 1).padStart(2, "0");
  const d = String(date.getDate()).padStart(2, "0");
  return `${y}${m}${d}`;
}

/**
 * Format a Date as an ICS DATETIME value in UTC (YYYYMMDDTHHmmssZ).
 */
function formatICSDateTime(date: Date): string {
  return (
    date.getFullYear().toString() +
    String(date.getMonth() + 1).padStart(2, "0") +
    String(date.getDate()).padStart(2, "0") +
    "T" +
    String(date.getHours()).padStart(2, "0") +
    String(date.getMinutes()).padStart(2, "0") +
    String(date.getSeconds()).padStart(2, "0")
  );
}

/**
 * Escape text for ICS fields (fold long lines, escape special chars).
 */
function escapeICS(text: string): string {
  return text
    .replace(/\\/g, "\\\\")
    .replace(/;/g, "\\;")
    .replace(/,/g, "\\,")
    .replace(/\n/g, "\\n");
}

/**
 * Generate a UID for an ICS event.
 */
function generateUID(taskId: string): string {
  return `${taskId}-${Date.now()}@bosun.app`;
}

/**
 * Generate an .ics file string for upcoming maintenance tasks.
 * Each task with a nextDueDate becomes an all-day calendar event
 * with a reminder 1 week before.
 */
export function generateMaintenanceICS(tasks: CalendarTask[]): string {
  const now = new Date();
  const stamp = formatICSDateTime(now);

  const events = tasks
    .filter((t) => t.nextDueDate !== null)
    .map((t) => {
      const dueDate = t.nextDueDate!;
      const endDate = new Date(dueDate);
      endDate.setDate(endDate.getDate() + 1); // all-day events need end = start + 1

      const description = [
        t.notes ? t.notes : "",
        `Interval: every ${t.intervalMonths} month${t.intervalMonths === 1 ? "" : "s"}`,
        "Generated by Bosun",
      ]
        .filter(Boolean)
        .join("\\n");

      return [
        "BEGIN:VEVENT",
        `UID:${generateUID(t.id)}`,
        `DTSTAMP:${stamp}`,
        `DTSTART;VALUE=DATE:${formatICSDate(dueDate)}`,
        `DTEND;VALUE=DATE:${formatICSDate(endDate)}`,
        `SUMMARY:${escapeICS("Boat Maintenance: " + t.task)}`,
        `DESCRIPTION:${escapeICS(description)}`,
        // Alarm: 1 week before
        "BEGIN:VALARM",
        "TRIGGER:-P7D",
        "ACTION:DISPLAY",
        `DESCRIPTION:${escapeICS(t.task + " is due in 1 week")}`,
        "END:VALARM",
        "END:VEVENT",
      ].join("\r\n");
    });

  if (events.length === 0) {
    // Create a single placeholder if no tasks have due dates
    return [
      "BEGIN:VCALENDAR",
      "VERSION:2.0",
      "PRODID:-//Bosun//Maintenance//EN",
      "CALSCALE:GREGORIAN",
      "END:VCALENDAR",
    ].join("\r\n");
  }

  return [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Bosun//Maintenance//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    "X-WR-CALNAME:Bosun Maintenance Schedule",
    ...events,
    "END:VCALENDAR",
  ].join("\r\n");
}

/**
 * Trigger a browser download of an .ics file.
 */
export function downloadICS(icsContent: string, filename = "bosun-maintenance.ics"): void {
  const blob = new Blob([icsContent], { type: "text/calendar;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}
